# Theme supports custom buttons
buttons:
  - text: oSoWoSo
    href: https://osowoso.github.io
    
# remote theme
remote_theme: oSoWoSo/cayman-vb-dark

# web title
title: DistroHopper

# web desription
description: Quickly download, create and run VM of any#TODO operating system.

# Header buttons for downloads from github repo
show_downloads: true

# Header buttons link to github repo 
show_github: true

# Header buttons for google analytics 
#google_analytics:

# web PNG favicon
favicon: logo.svg

# Icon shown in header. From Fontawesome https://fontawesome.com/icons?m=free
#icon: fas fa-pencil-alt

# Colour gradient for the header
#header-colours: 
#  right: "#8a108c"
#  left: "#cc580c"
